/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appinventarishlf;

/**
 *
 * @author aryas
 */
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        showdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        realjudul = new javax.swing.JLabel();
        btninventaris = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelinv = new javax.swing.JTable();
        invcepat = new javax.swing.JLabel();
        btnmember = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pemeliharaan Pegasus");
        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setText("Aplikasi Pemeliharaan");
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        realjudul.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        realjudul.setText("Nutrition Club Pegasus");
        getContentPane().add(realjudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 190, -1));

        btninventaris.setText("Edit Inventaris");
        btninventaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninventarisActionPerformed(evt);
            }
        });
        getContentPane().add(btninventaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        tabelinv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tabelinv);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 400, 120));

        invcepat.setText("Inventaris Cepat");
        getContentPane().add(invcepat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btnmember.setText("Daftar Member");
        btnmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appinventarishlf/pngwing.com.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninventarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninventarisActionPerformed
        Inventaris inv = new Inventaris();
        inv.setVisible(true);
        inv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        inv.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                showdata();
            }
        });
    }//GEN-LAST:event_btninventarisActionPerformed

    private void btnmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemberActionPerformed
        Member inv = new Member();
        inv.setVisible(true);
        inv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnmemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    public void showdata() {
        Connection con = new koneksi().GetConnection();
        ResultSet rs = null;
        PreparedStatement ps = null;
        DefaultTableModel model = (DefaultTableModel) tabelinv.getModel();
        model.setRowCount(0);
        try {
            String sql = "SELECT * FROM inventaris";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                String strkode = rs.getString("kode");
                String strnama = rs.getString("nama");
                int strint = rs.getInt("stok");
                Object[] row = {strkode, strnama, strint};
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan! \n" + e, "Perhatian", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninventaris;
    private javax.swing.JButton btnmember;
    private javax.swing.JLabel invcepat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel realjudul;
    private javax.swing.JTable tabelinv;
    // End of variables declaration//GEN-END:variables
}
